services:
  catalogdb:
    image: postgres:16

  basketdb:
    image: postgres:16
  
  orderingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  messagebroker:
    image: rabbitmq:management
    
  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
      
      
  ordering.api:
    image:  ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
volumes:
  postgres_catalog:
  postgres_basket:
  sqlserver_ordering:
